#define ZEN_FILTER_BUTTON_IDC 712300

#define ZEN_FILTER_LOG_LEVEL_ERROR 0
#define ZEN_FILTER_LOG_LEVEL_WARN 1
#define ZEN_FILTER_LOG_LEVEL_INFO 2
#define ZEN_FILTER_LOG_LEVEL_DEBUG 3
#define ZEN_FILTER_LOG_LEVEL_TRACE 4
